# Generated by the protobuf compile. DO NOT EDIT!

defmodule Inventory.InventoryService do
  @moduledoc false
  use Twirp.Service

  package "sahara.inventory"
  service "Inventory"

  rpc :GetCount, Sahara.Inventory.Item, Sahara.Inventory.Count, :get_count
end

defmodule Inventory.InventoryClient do
  @moduledoc false
  use Twirp.Client, service: Inventory.InventoryService
end
