# Generated by the protobuf compile. DO NOT EDIT!

defmodule Sahara.Catalog.CatalogService do
  @moduledoc false
  use Twirp.Service

  package "sahara.catalog"
  service "Catalog"

  rpc :GetItem, Sahara.Catalog.ItemReq, Sahara.Catalog.Item, :get_item
  rpc :GetItems, Sahara.Catalog.ItemsReq, Sahara.Catalog.ItemsResp, :get_items
end

defmodule Sahara.Catalog.CatalogClient do
  @moduledoc false
  use Twirp.Client, service: Sahara.Catalog.CatalogService
end
